### ISSUE TITLE
Make application to work with different types of templates

### ISSUE THREAD

**Issue by makkoncept** [brettvanderwerff/Flaskerizer#29]
While the application is working properly with templates from [bootsrapmade](https://bootstrapmade.com/) . there are some templates where it still needs some work as the styles. Few of them are

- [Alstar](https://bootstrapmade.com/alstar-free-parallax-bootstrap-template/)
- [sailor template](https://bootstrapmade.com/sailor-free-bootstrap-theme/)
- [NiceAdmin]( https://bootstrapmade.com/nice-admin-bootstrap-admin-html-template/)
- [Reveal](https://bootstrapmade.com/reveal-bootstrap-corporate-template/) 
-  [squadfree](https://bootstrapmade.com/squadfree-free-bootstrap-template-creative/)

Dig into the application to find the changes that need to be made to make them work properly, so that all the styles are present and the links are not broken

**Comment by brettvanderwerff** [comment]
@makkoncept see my comments on #20 about browser cache, all of these work for me with flaskerizer except alstar. NiceAdmin is a massive site so I was  really excited to see it work. There are a few 404's that come up in the terminal like `/img/avatar-mini.jpg HTTP/1.1" 404 -`, which I think might actually be links in the javascript that need to be fixed, but I'm not sure. I think there might be a similar issue with javascript on Alstar because the links that pop up as 404 in the terminal can only be found in the js files as far as I can see, not the html. I might be wrong on that though. Also, let me know if I missed any of the comments you made o any other issues, you were pretty active last night I don't want to miss anything.

**Comment by brettvanderwerff** [comment]
@makkoncept see issue #31, I just found out that parts of alstar do not work because of javascript links that need to be changed. We need to write a method that parses javascript files and changes links to point to items in the static folder similar to how we are parsing html links right now.

**Comment by brettvanderwerff** [comment]
@makkoncept Im closing this because we have all these working except for NiceAdmin, which I raised an issue for. I'm going to open an official running issue for people to post templates that don't work though
